name: Upload Python Package

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    
    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -

    - name: Install dependencies
      run: |
        poetry install
    
    - name: Build the package
      run: |
        poetry build

    # - name: Test with pytest
    #   run: |
    #     poetry run pytest -v
      
    - name: Publish to PyPI
      env:
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        USERNAME: __token__
      run: |
        poetry publish --username $USERNAME --password $TWINE_PASSWORD